In [1]:
from dotenv import load_dotenv
from pathlib import Path

load_dotenv(Path.home() / "fmri-fm/.env")

True

In [2]:
from functools import partial
from itertools import product
import json

import torch
import pandas as pd
from omegaconf import OmegaConf

from data.flat_data import FlatClipsDataset, make_flat_transform
import flat_mae.models_mae as models_mae
import flat_mae.masking as masking
import flat_mae.utils as ut

In [18]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(device)

cuda

In [78]:
def make_loader(name: str):
    urls = {
        "hcp": "s3://medarc/fmri-fm/datasets/flat-clips/hcp-val-clips-16t",
        "nsd": "s3://medarc/fmri-fm/datasets/flat-clips/nsd-subj01-clips-16t",
        "ukbb": "s3://sophont/fmri-fm/datasets/flat-clips/ukbb-val-clips-mini-16t",
    }

    transform = make_flat_transform(img_size=(224, 560), normalize="frame")
    dataset = FlatClipsDataset(urls[name], transform=transform)

    mask_fn = masking.TubeMasking(
        mask_ratio=0.9,
        img_size=(224, 560),
        patch_size=16,
        num_frames=16,
        t_patch_size=4,
    )

    loader = torch.utils.data.DataLoader(
        dataset,
        batch_size=32,
        shuffle=False,
        collate_fn=partial(masking.mask_collate, mask_fn=mask_fn),
        num_workers=8,
        drop_last=True,
    )
    return loader

In [79]:
def load_model(ckpt_path: Path, **kwargs):
    ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=True)
    cfg = OmegaConf.create(ckpt["args"])
    model_kwargs = cfg.model_kwargs.copy()
    model_kwargs.update(kwargs)
    model = models_mae.__dict__[cfg.model](
        img_size=cfg.img_size,
        in_chans=cfg.in_chans,
        patch_size=cfg.patch_size,
        num_frames=cfg.num_frames,
        t_patch_size=cfg.t_patch_size,
        **model_kwargs,
    )
    model.load_state_dict(ckpt["model"])
    return model

In [80]:
@torch.inference_mode()
def evaluate(model, loader, device):
    torch.manual_seed(42)
    logger = ut.MetricLogger(delimiter="  ")
    for batch in logger.log_every(loader, print_freq=20, header="eval"):
        batch = ut.send_data(batch, device)

        x = batch["image"]
        mask = batch["img_mask"]
        visible_mask = batch["visible_mask"]

        with torch.autocast(device_type=device.type, dtype=torch.float16):
            loss = model(
                x, img_mask=mask, visible_mask=visible_mask, mask_ratio=None, with_state=False
            )
        logger.update(loss=loss.item())

    stats = {k: meter.global_avg for k, meter in logger.meters.items()}
    return stats

In [3]:
result_dir = Path("results/masked_recon")
result_dir.mkdir(exist_ok=True, parents=True)

keys = [
    "attn_reg-1",
    "cross_reg-1",
    "crossreg_reg-1",
    "crossreg_reg-4",
    "crossreg_reg-16",
    "attn_pep-4",
    "cross_pep-4",
    "crossreg_reg-4_pep-4",
]
peps = [0, 4]

In [ ]:
for ds in ["hcp", "nsd", "ukbb"]:
    loader = make_loader(ds)

    for key, pep in product(keys, peps):
        out_path = result_dir / f"{key}__pad-{pep}__{ds}.json"
        if out_path.exists():
            continue

        ckpt_path = f"checkpoints/decoders/{key}/pretrain/checkpoint-last.pth"
        model = load_model(ckpt_path, pred_edge_pad=pep)
        model.to(device)

        stats = evaluate(model, loader, device)
        record = {"dataset": ds, "key": key, "pad": pep, **stats}
        print(json.dumps(record))
        with out_path.open("w") as f:
            print(json.dumps(record), file=f)

eval  [ 0/81]  eta: 0:02:26  loss: 0.8318 (0.8318)  time: 1.8056  data: 1.7425  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8267 (0.8247)  time: 0.1116  data: 0.0499  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8243 (0.8211)  time: 0.1232  data: 0.0608  max mem: 4148
eval  [60/81]  eta: 0:00:02  loss: 0.8265 (0.8212)  time: 0.1101  data: 0.0475  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8302 (0.8231)  time: 0.1164  data: 0.0553  max mem: 4148
eval Total time: 0:00:11 (0.1381 s / it)
{"dataset": "hcp", "key": "attn_reg-1", "pad": 0, "loss": 0.8231088305697029}
eval  [ 0/81]  eta: 0:02:29  loss: 0.8771 (0.8771)  time: 1.8402  data: 1.7519  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8719 (0.8697)  time: 0.1111  data: 0.0457  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8699 (0.8660)  time: 0.1237  data: 0.0577  max mem: 4148
eval  [60/81]  eta: 0:00:03  loss: 0.8706 (0.8662)  time: 0.1116  data: 0.0464  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8769 (0.8682)  time: 0.1191  data: 0.0544  max mem: 4148
eval Total time: 0:00:11 (0.1393 s / it)
{"dataset": "hcp", "key": "attn_reg-1", "pad": 4, "loss": 0.868164700490457}
eval  [ 0/81]  eta: 0:02:28  loss: 0.8350 (0.8350)  time: 1.8393  data: 1.7597  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8298 (0.8295)  time: 0.1107  data: 0.0523  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8256 (0.8250)  time: 0.1256  data: 0.0673  max mem: 4148
eval  [60/81]  eta: 0:00:03  loss: 0.8307 (0.8254)  time: 0.1113  data: 0.0535  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8327 (0.8270)  time: 0.1223  data: 0.0649  max mem: 4148
eval Total time: 0:00:11 (0.1406 s / it)
{"dataset": "hcp", "key": "cross_reg-1", "pad": 0, "loss": 0.8269610669877794}
eval  [ 0/81]  eta: 0:02:27  loss: 0.8797 (0.8797)  time: 1.8195  data: 1.7567  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8743 (0.8739)  time: 0.1107  data: 0.0493  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8693 (0.8692)  time: 0.1233  data: 0.0603  max mem: 4148
eval  [60/81]  eta: 0:00:02  loss: 0.8743 (0.8697)  time: 0.1094  data: 0.0478  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8771 (0.8714)  time: 0.1172  data: 0.0563  max mem: 4148
eval Total time: 0:00:11 (0.1381 s / it)
{"dataset": "hcp", "key": "cross_reg-1", "pad": 4, "loss": 0.871351796903728}
eval  [ 0/81]  eta: 0:02:27  loss: 0.8827 (0.8827)  time: 1.8200  data: 1.7318  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8786 (0.8765)  time: 0.1093  data: 0.0517  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8794 (0.8742)  time: 0.1244  data: 0.0662  max mem: 4148
eval  [60/81]  eta: 0:00:02  loss: 0.8805 (0.8743)  time: 0.1093  data: 0.0518  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8826 (0.8763)  time: 0.1204  data: 0.0633  max mem: 4148
eval Total time: 0:00:11 (0.1389 s / it)
{"dataset": "hcp", "key": "crossreg_reg-1", "pad": 0, "loss": 0.8762572930182939}
eval  [ 0/81]  eta: 0:02:22  loss: 0.8874 (0.8874)  time: 1.7582  data: 1.6964  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8831 (0.8817)  time: 0.1109  data: 0.0502  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8848 (0.8791)  time: 0.1222  data: 0.0607  max mem: 4148
eval  [60/81]  eta: 0:00:02  loss: 0.8852 (0.8792)  time: 0.1095  data: 0.0487  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8890 (0.8812)  time: 0.1160  data: 0.0562  max mem: 4148
eval Total time: 0:00:11 (0.1370 s / it)
{"dataset": "hcp", "key": "crossreg_reg-1", "pad": 4, "loss": 0.881170368488924}
eval  [ 0/81]  eta: 0:02:25  loss: 0.8757 (0.8757)  time: 1.7951  data: 1.7378  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8708 (0.8718)  time: 0.1117  data: 0.0543  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8691 (0.8671)  time: 0.1235  data: 0.0655  max mem: 4148
eval  [60/81]  eta: 0:00:02  loss: 0.8722 (0.8672)  time: 0.1089  data: 0.0513  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8739 (0.8688)  time: 0.1184  data: 0.0607  max mem: 4148
eval Total time: 0:00:11 (0.1383 s / it)
{"dataset": "hcp", "key": "crossreg_reg-4", "pad": 0, "loss": 0.8688115749830081}
eval  [ 0/81]  eta: 0:02:25  loss: 0.8829 (0.8829)  time: 1.7997  data: 1.7124  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8783 (0.8799)  time: 0.1121  data: 0.0512  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8768 (0.8750)  time: 0.1228  data: 0.0616  max mem: 4148
eval  [60/81]  eta: 0:00:03  loss: 0.8792 (0.8750)  time: 0.1110  data: 0.0498  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8838 (0.8767)  time: 0.1178  data: 0.0581  max mem: 4148
eval Total time: 0:00:11 (0.1387 s / it)
{"dataset": "hcp", "key": "crossreg_reg-4", "pad": 4, "loss": 0.8766809532671799}
eval  [ 0/81]  eta: 0:02:26  loss: 0.8732 (0.8732)  time: 1.8036  data: 1.7147  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8683 (0.8667)  time: 0.1096  data: 0.0519  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8639 (0.8631)  time: 0.1257  data: 0.0680  max mem: 4148
eval  [60/81]  eta: 0:00:02  loss: 0.8673 (0.8637)  time: 0.1092  data: 0.0517  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8705 (0.8652)  time: 0.1199  data: 0.0633  max mem: 4148
eval Total time: 0:00:11 (0.1389 s / it)
{"dataset": "hcp", "key": "crossreg_reg-16", "pad": 0, "loss": 0.8651511264436039}
eval  [ 0/81]  eta: 0:02:27  loss: 0.8834 (0.8834)  time: 1.8219  data: 1.7328  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8788 (0.8777)  time: 0.1113  data: 0.0499  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8748 (0.8739)  time: 0.1228  data: 0.0615  max mem: 4148
eval  [60/81]  eta: 0:00:03  loss: 0.8802 (0.8745)  time: 0.1115  data: 0.0493  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8838 (0.8760)  time: 0.1163  data: 0.0564  max mem: 4148
eval Total time: 0:00:11 (0.1386 s / it)
{"dataset": "hcp", "key": "crossreg_reg-16", "pad": 4, "loss": 0.8760321890866315}
eval  [ 0/81]  eta: 0:02:24  loss: 0.8724 (0.8724)  time: 1.7867  data: 1.7251  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8689 (0.8660)  time: 0.1122  data: 0.0505  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8621 (0.8618)  time: 0.1230  data: 0.0613  max mem: 4148
eval  [60/81]  eta: 0:00:03  loss: 0.8672 (0.8620)  time: 0.1121  data: 0.0493  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8688 (0.8637)  time: 0.1172  data: 0.0564  max mem: 4148
eval Total time: 0:00:11 (0.1388 s / it)
{"dataset": "hcp", "key": "attn_pep-4", "pad": 0, "loss": 0.8637438269309056}
eval  [ 0/81]  eta: 0:02:22  loss: 0.8783 (0.8783)  time: 1.7633  data: 1.6967  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8743 (0.8724)  time: 0.1130  data: 0.0474  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8687 (0.8682)  time: 0.1224  data: 0.0565  max mem: 4148
eval  [60/81]  eta: 0:00:02  loss: 0.8731 (0.8684)  time: 0.1121  data: 0.0461  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8784 (0.8702)  time: 0.1172  data: 0.0527  max mem: 4148
eval Total time: 0:00:11 (0.1384 s / it)
{"dataset": "hcp", "key": "attn_pep-4", "pad": 4, "loss": 0.8701631338508041}
eval  [ 0/81]  eta: 0:02:27  loss: 0.8767 (0.8767)  time: 1.8263  data: 1.7676  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8703 (0.8706)  time: 0.1118  data: 0.0537  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8671 (0.8659)  time: 0.1242  data: 0.0656  max mem: 4148
eval  [60/81]  eta: 0:00:03  loss: 0.8689 (0.8666)  time: 0.1098  data: 0.0517  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8715 (0.8681)  time: 0.1211  data: 0.0636  max mem: 4148
eval Total time: 0:00:11 (0.1399 s / it)
{"dataset": "hcp", "key": "cross_pep-4", "pad": 0, "loss": 0.868062961248704}
eval  [ 0/81]  eta: 0:02:24  loss: 0.8818 (0.8818)  time: 1.7832  data: 1.7208  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8759 (0.8765)  time: 0.1128  data: 0.0514  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8726 (0.8716)  time: 0.1246  data: 0.0624  max mem: 4148
eval  [60/81]  eta: 0:00:03  loss: 0.8742 (0.8724)  time: 0.1105  data: 0.0489  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8795 (0.8739)  time: 0.1185  data: 0.0576  max mem: 4148
eval Total time: 0:00:11 (0.1391 s / it)
{"dataset": "hcp", "key": "cross_pep-4", "pad": 4, "loss": 0.8738854667286814}
eval  [ 0/81]  eta: 0:02:27  loss: 0.8794 (0.8794)  time: 1.8186  data: 1.7603  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8744 (0.8755)  time: 0.1120  data: 0.0538  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8728 (0.8712)  time: 0.1258  data: 0.0669  max mem: 4148
eval  [60/81]  eta: 0:00:03  loss: 0.8751 (0.8716)  time: 0.1095  data: 0.0512  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8801 (0.8732)  time: 0.1178  data: 0.0597  max mem: 4148
eval Total time: 0:00:11 (0.1394 s / it)
{"dataset": "hcp", "key": "crossreg_reg-4_pep-4", "pad": 0, "loss": 0.8731860099015413}
eval  [ 0/81]  eta: 0:02:25  loss: 0.8833 (0.8833)  time: 1.7954  data: 1.7106  max mem: 4148
eval  [20/81]  eta: 0:00:11  loss: 0.8784 (0.8799)  time: 0.1107  data: 0.0485  max mem: 4148
eval  [40/81]  eta: 0:00:06  loss: 0.8765 (0.8753)  time: 0.1238  data: 0.0618  max mem: 4148
eval  [60/81]  eta: 0:00:03  loss: 0.8792 (0.8757)  time: 0.1122  data: 0.0488  max mem: 4148
eval  [80/81]  eta: 0:00:00  loss: 0.8853 (0.8774)  time: 0.1165  data: 0.0554  max mem: 4148
eval Total time: 0:00:11 (0.1386 s / it)
{"dataset": "hcp", "key": "crossreg_reg-4_pep-4", "pad": 4, "loss": 0.8773593365410228}
eval  [ 0/67]  eta: 0:02:01  loss: 0.8575 (0.8575)  time: 1.8174  data: 1.7552  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8347 (0.8391)  time: 0.1119  data: 0.0499  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8301 (0.8347)  time: 0.1226  data: 0.0606  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8258 (0.8331)  time: 0.1112  data: 0.0476  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8313 (0.8336)  time: 0.1192  data: 0.0563  max mem: 4148
eval Total time: 0:00:09 (0.1431 s / it)
{"dataset": "nsd", "key": "attn_reg-1", "pad": 0, "loss": 0.8335675152380075}
eval  [ 0/67]  eta: 0:02:00  loss: 0.9008 (0.9008)  time: 1.7974  data: 1.7324  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8781 (0.8820)  time: 0.1148  data: 0.0481  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8743 (0.8783)  time: 0.1240  data: 0.0572  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8720 (0.8769)  time: 0.1123  data: 0.0471  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8756 (0.8772)  time: 0.1197  data: 0.0549  max mem: 4148
eval Total time: 0:00:09 (0.1444 s / it)
{"dataset": "nsd", "key": "attn_reg-1", "pad": 4, "loss": 0.8772446619930552}
eval  [ 0/67]  eta: 0:02:01  loss: 0.8598 (0.8598)  time: 1.8109  data: 1.7329  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8372 (0.8410)  time: 0.1116  data: 0.0530  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8312 (0.8367)  time: 0.1243  data: 0.0667  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8290 (0.8351)  time: 0.1114  data: 0.0532  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8338 (0.8357)  time: 0.1210  data: 0.0642  max mem: 4148
eval Total time: 0:00:09 (0.1437 s / it)
{"dataset": "nsd", "key": "cross_reg-1", "pad": 0, "loss": 0.8357458274755905}
eval  [ 0/67]  eta: 0:01:57  loss: 0.9023 (0.9023)  time: 1.7506  data: 1.6877  max mem: 4148
eval  [20/67]  eta: 0:00:08  loss: 0.8800 (0.8830)  time: 0.1124  data: 0.0502  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8762 (0.8794)  time: 0.1230  data: 0.0608  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8722 (0.8780)  time: 0.1144  data: 0.0517  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8760 (0.8785)  time: 0.1233  data: 0.0610  max mem: 4148
eval Total time: 0:00:09 (0.1435 s / it)
{"dataset": "nsd", "key": "cross_reg-1", "pad": 4, "loss": 0.8785164107137652}
eval  [ 0/67]  eta: 0:02:02  loss: 0.8965 (0.8965)  time: 1.8229  data: 1.7646  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8753 (0.8793)  time: 0.1120  data: 0.0542  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8721 (0.8758)  time: 0.1238  data: 0.0663  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8673 (0.8742)  time: 0.1114  data: 0.0535  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8708 (0.8746)  time: 0.1223  data: 0.0648  max mem: 4148
eval Total time: 0:00:09 (0.1438 s / it)
{"dataset": "nsd", "key": "crossreg_reg-1", "pad": 0, "loss": 0.8745759814532835}
eval  [ 0/67]  eta: 0:02:02  loss: 0.9050 (0.9050)  time: 1.8341  data: 1.7711  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8831 (0.8871)  time: 0.1109  data: 0.0505  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8782 (0.8835)  time: 0.1226  data: 0.0614  max mem: 4148
eval  [60/67]  eta: 0:00:00  loss: 0.8757 (0.8820)  time: 0.1103  data: 0.0499  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8789 (0.8823)  time: 0.1210  data: 0.0609  max mem: 4148
eval Total time: 0:00:09 (0.1435 s / it)
{"dataset": "nsd", "key": "crossreg_reg-1", "pad": 4, "loss": 0.8822886249912318}
eval  [ 0/67]  eta: 0:02:01  loss: 0.8946 (0.8946)  time: 1.8128  data: 1.7558  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8747 (0.8775)  time: 0.1117  data: 0.0542  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8695 (0.8733)  time: 0.1252  data: 0.0667  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8652 (0.8717)  time: 0.1095  data: 0.0517  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8693 (0.8721)  time: 0.1198  data: 0.0628  max mem: 4148
eval Total time: 0:00:09 (0.1435 s / it)
{"dataset": "nsd", "key": "crossreg_reg-4", "pad": 0, "loss": 0.8721362014315022}
eval  [ 0/67]  eta: 0:02:02  loss: 0.9071 (0.9071)  time: 1.8269  data: 1.7661  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8869 (0.8897)  time: 0.1119  data: 0.0509  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8818 (0.8857)  time: 0.1259  data: 0.0645  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8782 (0.8842)  time: 0.1102  data: 0.0496  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8808 (0.8846)  time: 0.1209  data: 0.0609  max mem: 4148
eval Total time: 0:00:09 (0.1443 s / it)
{"dataset": "nsd", "key": "crossreg_reg-4", "pad": 4, "loss": 0.8845876793363201}
eval  [ 0/67]  eta: 0:02:00  loss: 0.8916 (0.8916)  time: 1.7964  data: 1.7384  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8683 (0.8722)  time: 0.1133  data: 0.0545  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8659 (0.8689)  time: 0.1227  data: 0.0644  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8609 (0.8676)  time: 0.1104  data: 0.0515  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8663 (0.8681)  time: 0.1202  data: 0.0626  max mem: 4148
eval Total time: 0:00:09 (0.1434 s / it)
{"dataset": "nsd", "key": "crossreg_reg-16", "pad": 0, "loss": 0.8680729581348932}
eval  [ 0/67]  eta: 0:02:02  loss: 0.9073 (0.9073)  time: 1.8300  data: 1.7530  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8849 (0.8879)  time: 0.1116  data: 0.0494  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8819 (0.8848)  time: 0.1230  data: 0.0608  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8772 (0.8836)  time: 0.1116  data: 0.0491  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8815 (0.8841)  time: 0.1213  data: 0.0592  max mem: 4148
eval Total time: 0:00:09 (0.1438 s / it)
{"dataset": "nsd", "key": "crossreg_reg-16", "pad": 4, "loss": 0.8840563501884688}
eval  [ 0/67]  eta: 0:02:01  loss: 0.8932 (0.8932)  time: 1.8186  data: 1.7556  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8665 (0.8726)  time: 0.1112  data: 0.0486  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8640 (0.8687)  time: 0.1214  data: 0.0585  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8610 (0.8673)  time: 0.1129  data: 0.0497  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8658 (0.8678)  time: 0.1209  data: 0.0581  max mem: 4148
eval Total time: 0:00:09 (0.1429 s / it)
{"dataset": "nsd", "key": "attn_pep-4", "pad": 0, "loss": 0.8677579404702828}
eval  [ 0/67]  eta: 0:02:02  loss: 0.9054 (0.9054)  time: 1.8326  data: 1.7663  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8780 (0.8839)  time: 0.1129  data: 0.0472  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8765 (0.8803)  time: 0.1223  data: 0.0563  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8739 (0.8790)  time: 0.1102  data: 0.0449  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8769 (0.8794)  time: 0.1192  data: 0.0537  max mem: 4148
eval Total time: 0:00:09 (0.1437 s / it)
{"dataset": "nsd", "key": "attn_pep-4", "pad": 4, "loss": 0.8794477679836217}
eval  [ 0/67]  eta: 0:02:02  loss: 0.9001 (0.9001)  time: 1.8344  data: 1.7749  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8763 (0.8802)  time: 0.1122  data: 0.0540  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8729 (0.8767)  time: 0.1260  data: 0.0675  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8697 (0.8755)  time: 0.1108  data: 0.0522  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8725 (0.8759)  time: 0.1211  data: 0.0632  max mem: 4148
eval Total time: 0:00:09 (0.1447 s / it)
{"dataset": "nsd", "key": "cross_pep-4", "pad": 0, "loss": 0.8758826771778847}
eval  [ 0/67]  eta: 0:02:04  loss: 0.9118 (0.9118)  time: 1.8531  data: 1.7903  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8876 (0.8912)  time: 0.1126  data: 0.0507  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8846 (0.8879)  time: 0.1256  data: 0.0624  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8822 (0.8868)  time: 0.1104  data: 0.0486  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8840 (0.8872)  time: 0.1192  data: 0.0583  max mem: 4148
eval Total time: 0:00:09 (0.1447 s / it)
{"dataset": "nsd", "key": "cross_pep-4", "pad": 4, "loss": 0.8872004774079394}
eval  [ 0/67]  eta: 0:02:05  loss: 0.8995 (0.8995)  time: 1.8725  data: 1.7948  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8776 (0.8803)  time: 0.1109  data: 0.0524  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8739 (0.8767)  time: 0.1263  data: 0.0678  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8694 (0.8754)  time: 0.1099  data: 0.0524  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8715 (0.8757)  time: 0.1206  data: 0.0639  max mem: 4148
eval Total time: 0:00:09 (0.1445 s / it)
{"dataset": "nsd", "key": "crossreg_reg-4_pep-4", "pad": 0, "loss": 0.875685675820308}
eval  [ 0/67]  eta: 0:02:00  loss: 0.9080 (0.9080)  time: 1.7968  data: 1.7212  max mem: 4148
eval  [20/67]  eta: 0:00:09  loss: 0.8862 (0.8883)  time: 0.1122  data: 0.0503  max mem: 4148
eval  [40/67]  eta: 0:00:04  loss: 0.8815 (0.8847)  time: 0.1234  data: 0.0614  max mem: 4148
eval  [60/67]  eta: 0:00:01  loss: 0.8784 (0.8835)  time: 0.1105  data: 0.0495  max mem: 4148
eval  [66/67]  eta: 0:00:00  loss: 0.8799 (0.8838)  time: 0.1200  data: 0.0600  max mem: 4148
eval Total time: 0:00:09 (0.1429 s / it)
{"dataset": "nsd", "key": "crossreg_reg-4_pep-4", "pad": 4, "loss": 0.8837896798973652}
eval  [ 0/84]  eta: 0:02:32  loss: 0.7092 (0.7092)  time: 1.8134  data: 1.7505  max mem: 4148
eval  [20/84]  eta: 0:00:12  loss: 0.7499 (0.7439)  time: 0.1128  data: 0.0502  max mem: 4148
eval  [40/84]  eta: 0:00:07  loss: 0.7367 (0.7462)  time: 0.1244  data: 0.0615  max mem: 4148
eval  [60/84]  eta: 0:00:03  loss: 0.7553 (0.7472)  time: 0.1125  data: 0.0495  max mem: 4148
eval  [80/84]  eta: 0:00:00  loss: 0.7441 (0.7477)  time: 0.1214  data: 0.0587  max mem: 4148
eval  [83/84]  eta: 0:00:00  loss: 0.7341 (0.7461)  time: 0.1210  data: 0.0588  max mem: 4148
eval Total time: 0:00:11 (0.1386 s / it)
{"dataset": "ukbb", "key": "attn_reg-1", "pad": 0, "loss": 0.7461191458361489}
eval  [ 0/84]  eta: 0:02:31  loss: 0.7720 (0.7720)  time: 1.8059  data: 1.7169  max mem: 4148
eval  [20/84]  eta: 0:00:12  loss: 0.8133 (0.8071)  time: 0.1151  data: 0.0491  max mem: 4148
eval  [40/84]  eta: 0:00:07  loss: 0.8007 (0.8096)  time: 0.1242  data: 0.0583  max mem: 4148

In [4]:
records = []

for ds in ["hcp", "nsd", "ukbb"]:
    for key, pep in product(keys, peps):
        out_path = result_dir / f"{key}__pad-{pep}__{ds}.json"
        with out_path.open() as f:
            record = json.load(f)
        records.append(record)

df = pd.DataFrame.from_records(records)

In [7]:
print(df.shape)
df.head()
df.to_csv("results/masked_recon.csv", index=False)

(48, 4)

In [ ]:
subdf = df.pivot_table(values="loss", index="key", columns=["dataset", "pad"], sort=False)
subdf = subdf.iloc[[0, 1, 4, 3, 2, 5, 6, 7], [1, 3, 5]]
subdf = subdf.reset_index()
subdf.columns = ["key", "HCP", "NSD", "UKBB"]
subdf["model"] = [k.split("_")[0] for k in subdf["key"]]
subdf["reg"] = [k.split("_")[0] for k in subdf["key"]]

                  model       HCP       NSD      UKBB
0            attn_reg-1  0.868165  0.877245  0.809438
1           cross_reg-1  0.871352  0.878516  0.812113
2       crossreg_reg-16  0.876032  0.884056  0.816919
3        crossreg_reg-4  0.876681  0.884588  0.818250
4        crossreg_reg-1  0.881170  0.882289  0.823008
5            attn_pep-4  0.870163  0.879448  0.814755
6           cross_pep-4  0.873885  0.887200  0.816136
7  crossreg_reg-4_pep-4  0.877359  0.883790  0.820925

dataset                    hcp       nsd      ukbb
pad                          4         4         4
key
attn_reg-1            0.868165  0.877245  0.809438
cross_reg-1           0.871352  0.878516  0.812113
crossreg_reg-16       0.876032  0.884056  0.816919
crossreg_reg-4        0.876681  0.884588  0.818250
crossreg_reg-1        0.881170  0.882289  0.823008
attn_pep-4            0.870163  0.879448  0.814755
cross_pep-4           0.873885  0.887200  0.816136
crossreg_reg-4_pep-4  0.877359  0.883790  0.820925

- nsd subj01 results

| model                |   loss (pad=0) |   loss (pad=4) |
|:---------------------|---------------:|---------------:|
| attn_reg-1           |         0.8336 |         0.8772 |
| attn_pep-4           |         0.8678 |         0.8794 |
| cross_reg-1          |         0.8357 |         0.8785 |
| cross_pep-4          |         0.8759 |         0.8872 |
| crossreg_reg-4       |         0.8721 |         0.8846 |
| crossreg_reg-4_pep-4 |         0.8757 |         0.8838 |

- ukbb val results

| model                |   loss (pad=0) |   loss (pad=4) |
|:---------------------|---------------:|---------------:|
| attn_reg-1           |         0.7461 |         0.8094 |
| attn_pep-4           |         0.8044 |         0.8148 |
| cross_reg-1          |         0.7497 |         0.8121 |
| cross_pep-4          |         0.8063 |         0.8161 |
| crossreg_reg-4       |         0.8075 |         0.8183 |
| crossreg_reg-4_pep-4 |         0.8147 |         0.8209 |